### ISSUE TITLE
Multiple arguments

### ISSUE THREAD

**Issue by ad-m** [dominicrodger/django-tinycontent#2]
Hello,

I am would like as why limits templatetags to only one argument?

I think it is good idea to pass multiple arguments like django cache template tags. Then you can fg. pass requests.language_code for gain translated box. 

You should force_text all arguments and join by eg. ":".

Greetings,
Adam Dobrawy

**Comment by dominicrodger** [comment]
I like the idea of supporting blocks in multiple languages, so I'd be open to that being added (though I probably would leave this for someone else to work on, since this isn't something I'm in need of in my use of django-tinycontent). I'm less convinced of the need for passing multiple arguments to the template tags. What other use cases did you have in mind?

**Comment by ad-m** [comment]
If you can allow pass multiple arguments you can pass eg.:
- language code - for multilanguange object,
- pk of sites object (from django contrib sites) - for multisite
- both above,
- a lot more.

In this way you create very flexible object management.

Wysłano z urządzenia mobilnego.
20 lip 2015 9:20 PM "Dominic Rodger" <notifications@github.com> napisał(a):

**Comment by dominicrodger** [comment]
Implemented in #3.
