### ISSUE TITLE
Importer are not necessary

### ISSUE THREAD

**Issue by ad-m** [dominicrodger/django-tinycontent#9]
See django.utils.module_loading.import_string

**Comment by dominicrodger** [comment]
Thanks for filing this @ad-m!

``import_string`` isn't available until Django 1.7, so this would mean dropping support for earlier versions. Since we don't support Django 1.4 now, and Django 1.5 and 1.6 [aren't supported versions of Django now](https://www.djangoproject.com/download/) anyway this is probably OK.
